// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAasolXtTmdIN6zT_iqojsvFV7Bq99k1QI',
    appId: '1:377390608261:web:7500da084c85f0753a9eec',
    messagingSenderId: '377390608261',
    projectId: 'assigment-81d66',
    authDomain: 'assigment-81d66.firebaseapp.com',
    storageBucket: 'assigment-81d66.firebasestorage.app',
    measurementId: 'G-RYTV5YV8LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzvhXnnnr_uwrE4suX-dNvUoppmLVUZw',
    appId: '1:377390608261:android:d6ae1bf38ad5be173a9eec',
    messagingSenderId: '377390608261',
    projectId: 'assigment-81d66',
    storageBucket: 'assigment-81d66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-qpfPH8LN0kNnu47rsXB0NAupKsSsAhI',
    appId: '1:377390608261:ios:d9aa63cf6af3bcbe3a9eec',
    messagingSenderId: '377390608261',
    projectId: 'assigment-81d66',
    storageBucket: 'assigment-81d66.firebasestorage.app',
    iosClientId: '377390608261-rdovidpol3i0i0pmjd60a7b45ku4ru8n.apps.googleusercontent.com',
    iosBundleId: 'com.lvs.alive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-qpfPH8LN0kNnu47rsXB0NAupKsSsAhI',
    appId: '1:377390608261:ios:d9aa63cf6af3bcbe3a9eec',
    messagingSenderId: '377390608261',
    projectId: 'assigment-81d66',
    storageBucket: 'assigment-81d66.firebasestorage.app',
    iosClientId: '377390608261-rdovidpol3i0i0pmjd60a7b45ku4ru8n.apps.googleusercontent.com',
    iosBundleId: 'com.lvs.alive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAasolXtTmdIN6zT_iqojsvFV7Bq99k1QI',
    appId: '1:377390608261:web:7b2f1f8cf6bd580e3a9eec',
    messagingSenderId: '377390608261',
    projectId: 'assigment-81d66',
    authDomain: 'assigment-81d66.firebaseapp.com',
    storageBucket: 'assigment-81d66.firebasestorage.app',
    measurementId: 'G-NNQP7Y6D6F',
  );
}
